### ISSUE TITLE
Warning about missing or empty deletions manifest doesn't go away

### ISSUE THREAD

**Issue by abartov** [steveyegge/beads#394]
I installed a very early version of beads, and never used it at all. Today, I installed the latest and start using it.

```bd doctor``` warns about the following:

```
⚠ Warning: Missing or empty (may have pre-v0.25.0 deletions)
  Fix: Run 'bd doctor --fix' to hydrate deletions manifest from git history
```

But running ```bd doctor --fix``` results in:

```
Fixing Deletions Manifest...
  No new deleted issues found in git history
  ✓ Fixed
```

and yet the Diagnostics section includes:

```
 └ Deletions Manifest: Missing or empty (may have pre-v0.25.0 deletions) ⚠
     Deleted issues from before v0.25.0 are not tracked and may resurrect on sync

⚠ Warning: Missing or empty (may have pre-v0.25.0 deletions)
  Fix: Run 'bd doctor --fix' to hydrate deletions manifest from git history

```

I have no old data or deletions, I just want this message to go away. :)

**Comment by steveyegge** [comment]
This was fixed in commit c3b4243. The doctor now only warns about the deletions manifest if there are actual pre-v0.25.0 deletions in git history that need to be tracked. Fresh installations or repos without deletions will no longer see this warning.

Thanks for reporting!

**Comment by abartov** [comment]
(suggesting re-open)

I just upgraded to v0.26.0, and the same issue has come back:

```
⚠ Warning: Missing or empty (may have pre-v0.25.0 deletions)
```

And ```bd doctor --fix``` does not resolve the issue, despite claiming to.

(and huge kudos for beads! I already adore it.)
